es_host: 192.168.1.124
es_port: 9200
name: Regla - correlacion eventos login
type: cardinality
cardinality_field: rule_name
max_cardinality: 1
filter:
 - terms:
     rule_name:
      - rule1
      - rule2
 - term:
      alert_sent: true
index: elastalert_status
timeframe:
  minutes: 30
