filebeat.prospectors:

- input_type: log
  paths:
    - /var/log/auth.log
  document_type: linux_auth 
#----------------------------- Logstash output --------------------------------
output.logstash:
  hosts: ["192.168.1.124:5045"]
