---

#   - apt_key:
#       keyserver: keyserver.ubuntu.com
#       id: EEA14886

   - name: Añadir repositorio java 8
     shell: add-apt-repository ppa:webupd8team/java

   - apt_repository:
       repo: deb http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main
       state: present
       filename: 'oracle_java'

   - apt_key:
       url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
       state: present

   - apt_repository:
       repo: deb https://artifacts.elastic.co/packages/5.x/apt stable main
       state: present
       filename: 'elastic'

   - name: Accept Java 8 License
     shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections

   - name: Instalacion de elasticsearch, logstash, kibana y filebeat
     apt:
       name: "{{ item }}"
       update_cache: yes
       allow_unauthenticated: yes
     with_items:
       - oracle-java8-installer
       - oracle-java8-set-default
       - elasticsearch
       - kibana
       - logstash
#       - filebeat

   - name: Instalacion metricbeat
     apt:
       name: metricbeat
     when: instalar_metricbeat == true

   - name: Configuracion elasticsearch.yml
     lineinfile:
       path: /etc/elasticsearch/elasticsearch.yml
       regexp: 'cluster.name:'
       line: 'cluster.name: {{ cluster_name }}'
       backup: yes

   - name: Configuracion elasticsearch.yml
     lineinfile:
       path: /etc/elasticsearch/elasticsearch.yml
       regexp: 'node.name:'   
       line: 'node.name: {{ ansible_hostname }}'
       backup: yes

   - name: Configuracion elasticsearch.yml
     lineinfile:
       path: /etc/elasticsearch/elasticsearch.yml
       regexp: 'network.host:'
       line: 'network.host: {{ ansible_default_ipv4.address }}'
       backup: yes

   - name: Configuracion kibana    
     lineinfile:
       path: /etc/kibana/kibana.yml
       regexp: 'server.host:'
       line: 'server.host: {{ ansible_default_ipv4.address }}'
       backup: yes

   - name: Configuracion kibana
     lineinfile:
       path: /etc/kibana/kibana.yml
       regexp: 'elasticsearch.url'
       line: 'elasticsearch.url: "http://{{ ansible_default_ipv4.address }}:9200"'
       backup: yes

   - name: Configuracion kibana
     lineinfile:
       path: /etc/kibana/kibana.yml
       regexp: 'logging.dest:'
       line: 'logging.dest: /var/log/kibana/kibana.log'
       backup: yes

   - name: Configuracion fichero 99-elasticsearch-output.conf
     copy:
       src: /etc/ansible/ficheros/logstash/99-elasticsearch-output.conf
       dest: /etc/logstash/conf.d/99-elasticsearch-output.conf

   - name: Configuracion fichero 40-osquery-sec-filter.conf
     copy:
       src: /etc/ansible/ficheros/logstash/40-osquery-sec-filter.conf
       dest: /etc/logstash/conf.d/40-osquery-sec-filter.conf

   - name: Configuracion fichero 02-beats-sec-input.conf
     copy:
       src: /etc/ansible/ficheros/logstash/02-beats-sec-input.conf
       dest: /etc/logstash/conf.d/02-beats-sec-input.conf

   - name: Creacion fichero log kibana
     lineinfile:
       path: /var/log/kibana/kibana.log
       line: ""
       create: yes
       owner: kibana
       group: kibana

#   - name: Copiar fichero configuracion filebeat
#     copy:
#       src: /etc/ansible/ficheros/filebeat/filebeat.yml.linux
#       dest: /etc/filebeat/filebeat.yml

#   - name: Modificar config filebeat para sec
#     blockinfile:
#       path: /etc/filebeat/filebeat.yml
#       insertafter: '  document_type: osquery'
#       block: |
#         - input_type: log
#           paths:
#             - /etc/sec/logs/SEC_alerts.log
#           document_type: sec_alerts

#   - name: Configuracion filebeat (comentar output elasticsearch)
#     replace:
#       path: /etc/filebeat/filebeat.yml
#       backup: yes
#       regexp: '(output.elasticsearch:)'
#       replace: '#\1'

#   - name: Configuracion filebeat (comentar hosts elasticsearch)
#     replace:
#       path: /etc/filebeat/filebeat.yml
#       backup: yes
#       regexp: '(hosts: \["localhost:9200"\])'
#       replace: '#\1'

#   - name: Configuracion filebeat (descomentar output logstash)
#     replace:
#       path: /etc/filebeat/filebeat.yml
#       backup: yes
#       regexp: '#(output.logstash:)'
#       replace: '\1'

#   - name: Configuracion filebeat (descomentar output logstash)
#     replace:
#       path: /etc/filebeat/filebeat.yml
#       backup: yes
#       regexp: '#(hosts: \["localhost:5044"\])'
#       replace: '\1'

   - name: Reiniciar servicios ELK
     service:
       name: "{{ item }}"
       state: restarted
     with_items:
       - elasticsearch
       - kibana
       - logstash
#       - filebeat
   - pause:
       seconds: 15

   - shell: dpkg -l|grep -i kibana|awk '{ print $3 }'
     register: kibana_version

   - name: Crear index osquery
     uri:
       url: http://{{ ansible_default_ipv4.address }}:9200/.kibana/index-pattern/{{ nombre_indice }}
       body:
         title: "{{ nombre_indice }}"
         timeFieldName: "@timestamp" 
       body_format: json
       method: PUT
       headers:
         Content-Type: "application/json"
       status_code: 201
     when: crear_indice == true

   - name: Crear default index pattern osquery
     uri:
       url: http://{{ ansible_default_ipv4.address }}:9200/.kibana/config/{{ kibana_version.stdout }}
       body:
         defaultIndex: "{{ nombre_indice }}"
       body_format: json
       method: PUT
     when: crear_indice == true
