---

  - name: Habilitar RDP Win10
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server
      name: fDenyTSConnections
      data: 0
      type: dword

  - name: Habilitar regla firewall RDP
    action: win_firewall_rule
    args:
      name: RDP
      enable: yes
      state: present
      localport: 3389
      action: allow
      direction: In
      protocol: TCP
      force: true
