---
    - win_service:
        name: w32time
        state: started
        start_mode: auto

    - win_shell: w32tm /config /syncfromflags:MANUAL /manualpeerlist:time.google.com

    - win_service:
        name: w32time
        state: restarted

    - win_shell: w32tm /resync
    - win_shell: w32tm /query /status
