---
  - win_domain_membership:
      dns_domain_name: "{{ dominio }}"
      hostname: "{{ nombre_maquina }}"
      domain_admin_user: Administrador@{{ dominio }}
      domain_admin_password: "{{ contrasena }}"
      state: domain
    register: domain_state

  - win_reboot:
    when: domain_state.reboot_required
